Repository sorocode/LetsTravel, pull requests merged in 2024-05, with the labels that each got.

#3 프론트엔드 밑바탕 작업
  src/main/frontend/index.html
  src/main/frontend/src/App.jsx
  src/main/frontend/src/assets/icons/add_icon.svg
  src/main/frontend/src/assets/icons/heart_blank.svg
  src/main/frontend/src/assets/icons/heart_filled.svg
  src/main/frontend/src/assets/icons/home_blank.svg
  src/main/frontend/src/assets/icons/home_filled.svg
  src/main/frontend/src/assets/icons/info_icon.svg
  src/main/frontend/src/assets/icons/map_blank.svg
  src/main/frontend/src/assets/icons/map_filled.svg
  src/main/frontend/src/assets/icons/navigator_blank.svg
  src/main/frontend/src/assets/icons/navigator_filled.svg
  src/main/frontend/src/assets/icons/profile_blank.svg
  src/main/frontend/src/assets/icons/profile_filled.svg
  src/main/frontend/src/assets/icons/react.svg
  src/main/frontend/src/assets/icons/search_icon.svg
  src/main/frontend/src/assets/images/bangkok.svg
  src/main/frontend/src/assets/images/beijing.svg
  src/main/frontend/src/assets/images/hanoi.svg
  src/main/frontend/src/assets/images/london.svg
  src/main/frontend/src/assets/images/newyork.svg
  src/main/frontend/src/assets/images/osaka.svg
  src/main/frontend/src/assets/images/tokyo.svg
  src/main/frontend/src/components/UI/CityItem.jsx
  src/main/frontend/src/components/UI/NavBar.jsx
  src/main/frontend/src/components/UI/SearchBar.jsx
  src/main/frontend/src/dummyCities.js
  src/main/frontend/src/index.css
  src/main/frontend/src/main.jsx
  src/main/frontend/src/pages/MapPage.jsx
  src/main/frontend/src/pages/RootLayout.jsx
  src/main/frontend/src/pages/SelectCityPage.jsx
  src/main/frontend/src/pages/SelectSpotPage.jsx
  src/main/frontend/src/pages/SelectTermPage.jsx
  src/main/frontend/src/store/schedule/scheduleSlice.js
  src/main/frontend/src/store/store.js
  src/main/frontend/src/util/router.jsx
  src/main/frontend/src/util/toMySQLDate.js
Labels: enhancement

#5 Feat/issue 4
  src/main/frontend/src/assets/icons/blue_check_icon.svg
  src/main/frontend/src/assets/icons/check_icon.svg
  src/main/frontend/src/components/UI/CityItem.jsx
  src/main/frontend/src/components/UI/SearchBar.jsx
  src/main/frontend/src/components/UI/SearchResults.jsx
  src/main/frontend/src/pages/SelectCityPage.jsx
Labels: enhancement

#7 🐛 Add forwardRef to SearchResults component
  src/main/frontend/src/components/UI/SearchResults.jsx
Labels: enhancement

#11 Feat/issue 8
  src/main/frontend/index.html
  src/main/frontend/src/components/UI/Bottomsheet/BottomSheet.jsx
  src/main/frontend/src/components/UI/Bottomsheet/DragHandle.jsx
  src/main/frontend/src/components/UI/Bottomsheet/DragHandleEdge.jsx
  src/main/frontend/src/components/UI/Bottomsheet/SheetHeader.jsx
  src/main/frontend/src/components/UI/Buttons/Button.jsx
  src/main/frontend/src/components/UI/SearchBar.jsx
  src/main/frontend/src/components/UI/SearchResults.jsx
  src/main/frontend/src/hooks/useBottomSheet.jsx
  src/main/frontend/src/hooks/usePrevious.jsx
  src/main/frontend/src/pages/SelectCityPage.jsx
Labels: enhancement

#10 ERD to SQL
  LetsTravelDB.sql
  LetsTravelERD.png
Labels: enhancement

#12 Feat/issue 9
  src/main/frontend/src/assets/icons/calendar_icon.svg
  src/main/frontend/src/colorPallete.js
  src/main/frontend/src/components/UI/Bottomsheet/BottomSheet.jsx
  src/main/frontend/src/components/UI/Bottomsheet/SheetHeader.jsx
  src/main/frontend/src/components/UI/Buttons/Button.jsx
  src/main/frontend/src/components/UI/Buttons/NonClickBtn.jsx
  src/main/frontend/src/components/UI/CityItem.jsx
  src/main/frontend/src/components/UI/DateInput.jsx
  src/main/frontend/src/components/UI/NavBar.jsx
  src/main/frontend/src/components/UI/SelectDateArea.jsx
  src/main/frontend/src/components/UI/SelectedCityList.jsx
  src/main/frontend/src/dummyCities.js
  src/main/frontend/src/pages/SelectCityPage.jsx
  src/main/frontend/src/pages/SelectTermPage.jsx
  src/main/frontend/src/store/schedule/scheduleSlice.js
  src/main/frontend/src/util/getDateDif.js
Labels: enhancement

#17 Feat/issue 14
  src/main/frontend/src/assets/icons/calendar_blank.svg
  src/main/frontend/src/assets/icons/dummy_image.svg
  src/main/frontend/src/assets/icons/earth_blank.svg
  src/main/frontend/src/assets/icons/earth_filled.svg
  src/main/frontend/src/assets/icons/map_blank.svg
  src/main/frontend/src/assets/icons/map_filled.svg
  src/main/frontend/src/assets/icons/map_indicator_blank.svg
  src/main/frontend/src/assets/icons/map_indicator_filled.svg
  src/main/frontend/src/assets/icons/up_rounded.svg
  src/main/frontend/src/components/UI/Bottomsheet/BottomSheet.jsx
  src/main/frontend/src/components/UI/Bottomsheet/SheetHeader.jsx
  src/main/frontend/src/components/UI/NavBar.jsx
  src/main/frontend/src/components/UI/SearchResults.jsx
  src/main/frontend/src/components/UI/SelectDateArea.jsx
  src/main/frontend/src/components/UI/SpotItem.jsx
  src/main/frontend/src/dummyCities.js
  src/main/frontend/src/hooks/useBottomSheet.jsx
  src/main/frontend/src/hooks/useToggleIcon.jsx
  src/main/frontend/src/pages/ProfilePage.jsx
  src/main/frontend/src/pages/SelectSpotPage.jsx
  src/main/frontend/src/store/navigation/navigationSlice.js
  src/main/frontend/src/store/store.js
  src/main/frontend/src/util/router.jsx
Labels: 🎨 Html&css, ✨ Feature

#19 Feat/issue 18
  src/main/frontend/package-lock.json
  src/main/frontend/package.json
  src/main/frontend/src/components/UI/Bottomsheet/BottomSheet.jsx
  src/main/frontend/src/components/UI/MapContainer.jsx
  src/main/frontend/src/pages/MapPage.jsx
  src/main/frontend/src/pages/RootLayout.jsx
  src/main/frontend/src/pages/SelectCityPage.jsx
  src/main/frontend/src/pages/SelectSpotPage.jsx
  src/main/frontend/src/store/schedule/scheduleSlice.js
Labels: 🎨 Html&css, ✨ Feature

#24 🐛 패딩 없애므로써 해결
  src/main/frontend/src/components/UI/NavBar.jsx
Labels: 🐞 BugFix

#28 Feat/issue 25
  src/main/frontend/.gitignore
  src/main/frontend/package-lock.json
  src/main/frontend/package.json
  src/main/frontend/src/App.jsx
  src/main/frontend/src/components/UI/CityItem.jsx
  src/main/frontend/src/countryData.js
  src/main/frontend/src/pages/SelectCityPage.jsx
  src/main/frontend/src/store/schedule/scheduleSlice.js
  src/main/frontend/src/util/http.js
Labels: 📬 API, ✨ Feature

#31 Feat/issue 29
  src/main/frontend/src/components/UI/CityItem.jsx
  src/main/frontend/src/components/UI/Error/ErrorPage.jsx
  src/main/frontend/src/components/UI/NavBar.jsx
  src/main/frontend/src/components/UI/SearchResults.jsx
  src/main/frontend/src/components/UI/SelectedCityList.jsx
  src/main/frontend/src/pages/IntroPage.jsx
  src/main/frontend/src/pages/RootLayout.jsx
  src/main/frontend/src/pages/SelectCityPage.jsx
  src/main/frontend/src/store/navigation/navigationSlice.js
  src/main/frontend/src/store/schedule/scheduleSlice.js
  src/main/frontend/src/util/http.js
  src/main/frontend/src/util/router.jsx
Labels: 🎨 Html&css, ✨ Feature

#35 Feat/issue 32
  src/main/frontend/src/components/UI/SearchBar.jsx
  src/main/frontend/src/components/UI/SearchResults.jsx
  src/main/frontend/src/components/UI/SpotItem.jsx
  src/main/frontend/src/hooks/useSearch.jsx
  src/main/frontend/src/pages/SelectCityPage.jsx
  src/main/frontend/src/pages/SelectSpotPage.jsx
  src/main/frontend/src/store/schedule/scheduleSlice.js
  src/main/frontend/src/util/http.js
Labels: 🎨 Html&css, 🔨 Refactor, ✨ Feature

#42 Feat/issue 22
  src/main/frontend/package-lock.json
  src/main/frontend/package.json
  src/main/frontend/src/assets/icons/spinner.gif
  src/main/frontend/src/components/UI/Buttons/ButtonSmall.jsx
  src/main/frontend/src/components/UI/Buttons/QuickSearchButton.jsx
  src/main/frontend/src/components/UI/NavBar.jsx
  src/main/frontend/src/components/UI/SearchBar.jsx
  src/main/frontend/src/components/UI/SearchResults.jsx
  src/main/frontend/src/hooks/useSearch.jsx
  src/main/frontend/src/pages/SelectSpotPage.jsx
  src/main/frontend/src/util/http.js
Labels: 🎨 Html&css, ✨ Feature

#43 Feat/issue 20
  src/main/frontend/index.html
  src/main/frontend/package-lock.json
  src/main/frontend/package.json
  src/main/frontend/public/logo.png
  src/main/frontend/src/assets/icons/goldtier.svg
  src/main/frontend/src/assets/images/1.jpg
  src/main/frontend/src/assets/images/plainview.jpg
  src/main/frontend/src/components/UI/Bottomsheet/BottomSheet.jsx
  src/main/frontend/src/components/UI/CityItem.jsx
  src/main/frontend/src/components/UI/Header.jsx
  src/main/frontend/src/components/UI/Itinery.jsx
  src/main/frontend/src/components/UI/MapContainer.jsx
  src/main/frontend/src/components/UI/NavBar.jsx
  src/main/frontend/src/components/UI/SearchBar.jsx
  src/main/frontend/src/components/UI/SearchResults.jsx
  src/main/frontend/src/components/UI/SelectDateArea.jsx
  src/main/frontend/src/components/UI/SelectedCityList.jsx
  src/main/frontend/src/components/UI/SpotItem.jsx
  src/main/frontend/src/countryData.js
  src/main/frontend/src/index.css
  src/main/frontend/src/pages/IntroPage.jsx
  src/main/frontend/src/pages/MapPage.jsx
  src/main/frontend/src/pages/ProfilePage.jsx
  src/main/frontend/src/pages/RootLayout.jsx
  src/main/frontend/src/pages/SelectCityPage.jsx
  src/main/frontend/src/pages/SelectSpotPage.jsx
  src/main/frontend/src/store/schedule/scheduleSlice.js
  src/main/frontend/src/util/http.js
  src/main/frontend/src/util/router.jsx
  src/main/frontend/tailwind.config.js
Labels: 🎨 Html&css, ✨ Feature

#46 Feat/issue 44
  src/main/frontend/package-lock.json
  src/main/frontend/package.json
  src/main/frontend/src/assets/icons/gptIcon.svg
  src/main/frontend/src/components/UI/Bottomsheet/BottomSheet.jsx
  src/main/frontend/src/components/UI/Bottomsheet/SheetHeader.jsx
  src/main/frontend/src/components/UI/CustomMarker.jsx
  src/main/frontend/src/components/UI/Header.jsx
  src/main/frontend/src/components/UI/Itinery.jsx
  src/main/frontend/src/components/UI/Logo.jsx
  src/main/frontend/src/components/UI/MapContainer.jsx
  src/main/frontend/src/components/UI/NavBar.jsx
  src/main/frontend/src/components/UI/ProfileSection.jsx
  src/main/frontend/src/pages/MapPage.jsx
  src/main/frontend/src/pages/ProfilePage.jsx
  src/main/frontend/src/pages/SelectSpotPage.jsx
  src/main/frontend/src/store/schedule/scheduleSlice.js
  src/main/frontend/src/util/http.js
Labels: 🎨 Html&css, 📬 API, ✨ Feature

#48 Feat/issue 47 일부 수정
  src/main/frontend/package-lock.json
  src/main/frontend/package.json
  src/main/frontend/public/imageSkeleton.svg
  src/main/frontend/public/suitcase.svg
  src/main/frontend/src/components/UI/Card/Card.jsx
  src/main/frontend/src/components/UI/Error/ErrorPage.jsx
  src/main/frontend/src/components/UI/Header.jsx
  src/main/frontend/src/components/UI/ProfileSection.jsx
  src/main/frontend/src/pages/MapPage.jsx
  src/main/frontend/src/pages/MyTripsPage.jsx
  src/main/frontend/src/pages/ProfilePage.jsx
  src/main/frontend/src/pages/SelectSpotPage.jsx
  src/main/frontend/src/pages/TripPage.jsx
  src/main/frontend/src/store/schedule/scheduleSlice.js
  src/main/frontend/src/util/getEndDate.js
  src/main/frontend/src/util/http.js
  src/main/frontend/src/util/router.jsx
Labels: 🎨 Html&css, 📬 API

#49 ✨place 추가 api 연동
  src/main/frontend/src/hooks/useSearch.jsx
  src/main/frontend/src/pages/SelectSpotPage.jsx
  src/main/frontend/src/util/http.js
  src/main/frontend/src/util/transformPlaceData.js
Labels: 📬 API
